openapi: 3.1.1
info:
  title: Euchre Manager
  description: >
    This is the API for the Euchmgr Manager admin functions.  The current working version
    (0.5) is based on the prototype admin UI, and not designed top-down.  We will work to
    make it cleaner and more RESTful, if supported by interest in creating alternative
    front-ends.  Note that there is a separate API for supporting mobile, player-centric
    applications.
  license:
    name: MIT License
    url: https://opensource.org/license/mit
  version: '0.5'

tags:
  - name: Security
    description: >-
      Admin authentication and session management.
  - name: Tournament
    description: >-
      Create and management tournaments and tournament parameters.
  - name: Players
    description: >-
      Manage tournament rosters and player information.  Also used to track player seeding
      round records and stats.
  - name: Seeding
    description: >-
      Manage seeding round brackets and game results.
  - name: Partners
    description: >-
      Manage the partner picking process.
  - name: Teams
    description: >-
      Manage team division assignments and seeding.  Also used to track team round robin
      records and stats.
  - name: Round Robin
    description: >-
      Manage round robin brackets and game results.
  - name: Final Four
    description: >-
      Track playoff team records and stats.
  - name: Playoffs
    description: >-
      Manage playoff brackets and game results.

paths:
  /login:
    post:
      tags:
        - Security
      summary: Authenticate admin user and create an app session.
      description:
      operationId: postLogin
      requestBody:
        required: true
        description: A JSON object containing the username and password.
        content:
          application/json:
            schema:
              type: object
              description: Login information.
              properties:
                username:
                  type: string
                  description: Admin username.
                  example: admin
                password:
                  type: string
                  description: Admin password.
                  example: <super-secret string>
      security: []  # no authentication
      responses:
        "200":
          description: >-
            Successfully authenticated.  The session ID is returned in a cookie named
            `session`.  This cookie must be passed in (in the HTTP header) for all
            subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=TGnTeNJk; Expires=26 Mar 2026 18:47:29 GMT; HttpOnly; Path=/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: null
                data: {"redirect": "/players"}
  /logout:
    post:
      tags:
        - Security
      summary: Terminate an admin session.
      Description:
      security:
        - cookieAuth: []
      responses:
        "200":
          description: >-
            Successfully logged out.  The session cookie is no longer valid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: User "Abs" logged out
                data: {"redirect": "/login"}
  /tourn/create_tourn:
    post:
      tags:
        - Tournament
      summary: Create a new tournament.
      description: Later, this action should be converted to a RESTful request.
      operationId: postCreateTourn
      requestBody:
        required: true
        description: Multipart form containing tournament field information.
        content:
          multipart/form-data:
            schema:
              type: object
              description: >-
                Note that these field names are slightly different than the tournament
                output fields.
              properties:
                tourn_name:
                  type: string
                  description: >-
                    Name of the new tournament to create.  The name can include spaces and
                    punctuation (other than the slash character ‘/’), and must be unique
                    across all tournaments.
                dates:
                  type: string
                  description: Timeframe information (for reference).
                venue:
                  type: string
                  description: Location information (for reference).
                dflt_pw:
                  type: string
                  description: >-
                    Default password for player (mobile app) logins.  If not specified,
                    then player passwords are not required for this tournament.
                overwrite:
                  type: boolean
                  description: Overwrite (replace) existing tournament with the same name.
                roster_file:
                  type: string
                  format: binary
                  description: Tournament roster as a CSV file upload.
              required:
                - tourn_name
                - roster_file
            example:
              tourn_name: NOLA 2025
              dates: Oct 24-25, 2025
              venue: Hotel St. Marie, New Orleans
              dflt_pw: <default password>
              overwrite: true
              roster_file: nola_2025_roster.csv
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A standard action response with the result of the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: null
                data: {"redirect": "/players"}
  /tourn/:
    get:
      tags:
        - Tournament
      summary: Get tournament data.
      description:
      operationId: getTourn
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with tournament information,
            including current stage.
          content:
            application/json:
              schema:
                type: object
                description: Response with tournament record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/TournData"
    post:
      tags:
        - Tournament
      summary: Update tournament data.
      description:
      operationId: postTourn
      requestBody:
        required: true
        description: A JSON object containing tournament data fields.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with the updated tournament
            information.
          content:
            application/json:
              schema:
                type: object
                description: Response with tournament record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/TournData"
  /tourn/pause_tourn:
    post:
      tags:
        - Tournament
      summary: Pause the operation of a currently active tournament.
      description: >-
        The tournament will be suspended and not accessible through the application until
        resumed.
      operationId: postPauseTourn
      requestBody:
        required: true
        description: A JSON object containing the name of the tournament.
        content:
          application/json:
            schema:
              type: object
              properties:
                tourn:
                  type: string
                  description: Name of the tournament to pause (suspend).
                  example: Nola 2025
              required:
                - tourn
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A standard action response with the result of the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: Tournament "Nola 2025" has been paused
                data: null
  /tourn/select_tourn:
    post:
      tags:
        - Tournament
      summary: Select and reactive the operation of an existing tournament.
      description: >-
        If a different tournament is currently in operation, it will be paused before the
        selected tournament is reactivated.  If the selected tournament is alredy active,
        this request is a no-op.
      operationId: postSelectTourn
      requestBody:
        required: true
        description: A JSON object containing the name of the tournament.
        content:
          application/json:
            schema:
              type: object
              properties:
                tourn:
                  type: string
                  description: Name of the tournament to activate (resume).
                  example: Nola 2025
              required:
                - tourn
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A standard action response with the result of the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: Resuming operation of tournament "Nola 2025"
                data: null
  /players/:
    get:
      tags:
        - Players
      summary: Get players data.
      description:
      operationId: getPlayers
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of player information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with players record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PlayerData"
    post:
      tags:
        - Players
      summary: Update player data.
      description:
      operationId: postPlayers
      requestBody:
        required: true
        description: >-
          A JSON object containing player data fields for the single record to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with player information for the
            updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with players record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/PlayerData"
  /players/gen_player_nums:
    post:
      tags:
        - Players
      summary: Generate "player number" identifiers.
      description: >-
        Player number identifiers are generated for all remaining players (those without
        numbers otherwise entered or assigned).
      operationId: postGenPlayerNums
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A standard action response with the result of the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: null
                data: {"redirect": "/players"}
  /players/gen_seed_bracket:
    post:
      tags:
        - Players
      summary: Generate seeding round bracket.
      description: >-
        Matchups are created from precomputed brackets (given number of players and
        rounds), with players assigned to games/seats based on their player number
        identifier.  Note that this request may only be made once player registration is
        complete, and all player numbers have been assigned or generated.
      operationId: postGenSeedBraacket
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A standard action response with the result of the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResp'
              example:
                succ: true
                err: null
                info: null
                data: {"redirect": "/seeding"}
  /seeding/:
    get:
      tags:
        - Seeding
      summary: Get seeding round data.
      description:
      operationId: getSeeding
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of seeding round game information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with seeding round game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SeedGameData"
    post:
      tags:
        - Seeding
      summary: Update seeding round game data.
      description:
      operationId: postSeeding
      requestBody:
        required: true
        description: >-
          A JSON object containing seeding round game fields for the single record to be
          updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeedGameData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with seeding round game
            information for the updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with seeding round game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/SeedGameData"
  /partners/:
    get:
      tags:
        - Partners
      summary: Get partners pikcing data.
      description:
      operationId: getPartners
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of player records, in order of partner
            picks (that is, seeding round player rankings).  Note that all players are
            listed, with an `available` flag indicating those players not yet on a team.
            The first available player is the one with the current pick.
          content:
            application/json:
              schema:
                type: object
                description: Response with partner picking data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PartnerData"
    post:
      tags:
        - Partners
      summary: Update partners data.
      description:
      operationId: postPartners
      requestBody:
        required: true
        description: >-
          A JSON object containing partner selection information for the player with the
          current pick.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartnerData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a directive for the client to reload the partner
            picks data (in order to pick up changes across multiple records).  Later, we
            may return the full data set, or perhaps just the changed records.
          content:
            application/json:
              schema:
                type: object
                description: Response with partner picking data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/ReloadObj"
  /teams/:
    get:
      tags:
        - Teams
      summary: Get teams data.
      description:
      operationId: getTeams
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of team information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with teams record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/TeamData"
    post:
      tags:
        - Teams
      summary: Update team data.
      description:
      operationId: postTeams
      requestBody:
        required: true
        description: >-
          A JSON object containing team data fields for the single record to be updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with team information for the
            updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with teams record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/TeamData"
  /round_robin/:
    get:
      tags:
        - Round Robin
      summary: Get round robin game data.
      description:
      operationId: getRoundRobin
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of round robin game information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with round robin game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/TournGameData"
    post:
      tags:
        - Round Robin
      summary: Update round robin game data.
      description:
      operationId: postRoundRobin
      requestBody:
        required: true
        description: >-
          A JSON object containing round robin game fields for the single record to be
          updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournGameData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with round robin game information
            for the updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with round robin game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/TournGameData"
  /final_four/:
    get:
      tags:
        - Final Four
      summary: Get final four team data.
      description:
      operationId: getFinalFour
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of final four team information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with final four team record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PlayoffTeamData"
    post:
      tags:
        - Final Four
      summary: Update final four team data.
      description:
      operationId: postFinalFour
      requestBody:
        required: true
        description: >-
          A JSON object containing final four team data fields for the single record to be
          updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayoffTeamData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with final four team information
            for the updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with final four team record data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/PlayoffTeamData"
  /playoffs/:
    get:
      tags:
        - Playoffs
      summary: Get playoffs game data.
      description:
      operationId: getPlayoffs
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains an array of playoffs game information records.
          content:
            application/json:
              schema:
                type: object
                description: Response with playoffs game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/PlayoffGameData"
    post:
      tags:
        - Playoffs
      summary: Update playoffs game data.
      description:
      operationId: postPlayoffs
      requestBody:
        required: true
        description: >-
          A JSON object containing playoffs game fields for the single record to be
          updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayoffGameData'
      security:
        - cookieAuth: []
      responses:
        '200':
          description: >-
            The `data` element contains a single record with playoffs game information
            for the updated record.
          content:
            application/json:
              schema:
                type: object
                description: Response with playoffs game data.
                properties:
                  succ:
                    $ref: "#/components/schemas/SuccElem"
                  err:
                    $ref: "#/components/schemas/ErrElem"
                  info:
                    $ref: "#/components/schemas/InfoElem"
                  data:
                    $ref: "#/components/schemas/PlayoffGameData"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
  schemas:
    SuccElem:
      type: boolean
      description: Value of `true` if request was successful.
    ErrElem:
      type: string
      description: >-
        Description of error, if `succ == false` (value of `null` if request was
        successful).
    InfoElem:
      type: string
      description: Informational message for successful requests.
    RedirectObj:
      type: object
      description: Non-binding directive to client for application area to redirect to.
      properties:
        redirect:
          type: string
          description: >-
            Name of the application area where the outcome of the action will be reflected
            (can be thought of as the target of a logical redirect).  The value actually
            corresponds to the URL (relative to endpoint root) of the suggested
            application "view".
          example: {"redirect": "/players"}
    ReloadObj:
      type: object
      description: >-
        Non-binding directive to client to reload the data for this application area.
      properties:
        reloadTable:
          type: boolean
          description: >-
            Indicates that the client-side data (typically a table or grid) should be
            reloaded (using the appropriate Ajax call).
          example: {"reloadTable": true}
    ActionResp:
      type: object
      description: >-
        Response structure for action requests, including indicator of success and a
        logical application redirect.
      properties:
        succ:
          $ref: "#/components/schemas/SuccElem"
        err:
          $ref: "#/components/schemas/ErrElem"
        info:
          $ref: "#/components/schemas/InfoElem"
        data:
          $ref: "#/components/schemas/RedirectObj"

    TournData:
      type: object
      description: Tournament information (updatable fields indicated).
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        name:
          type: string
          description: >-
            Name must be unique across all tournaments; name can include spaces and
            punctuation (other than the slash character ‘/’).
          example: NOLA 2025
        dates:
          type: string
          description: Timeframe information (updatable).
          example: Oct 24-25, 2025
        venue:
          type: string
          description: Location information, for reference (updatable).
          example: Hotel St. Marie, New Orleans
        cur_stage:
          type: string
          description: Current stage of the tournament.
          example: Round robin results completed
        next_action:
          type: string
          description: Action indicating the end of the current stage.
          example: Tabulate round robin results
        players:
          type: integer
          description: Number of players.
          example: 42
        teams:
          type: integer
          description: Number of teams.
          example: 20
        thm_teams:
          type: integer
          description: Number of "three-headed monster" teams.
          example: 2
        seed_rounds:
          type: integer
          description: Number of rounds in the seeding stage.
          example: 8
        tourn_rounds:
          type: integer
          description: Number of rounds in the round robin stage.
          example: 8
        divisions:
          type: integer
          description: Number of divisions for the round robin stage.
          example: 2
      additionalProperties: true
    PlayerData:
      type: object
      description: Player information and seeding stats (updatable fields indicated).
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        display_name:
          type: string
          description: >-
            Full name of player, composed of last name qualified by either first name or
            nick name (if specified).
          example: Abernathy (Abs)
        player_num:
          type: integer
          description: >-
            "Player number" identifier based on ping pong ball selection, or randomly
            generated values (updatable).  This identifier is used in assigning the player
            to seeding bracket matchups.
          example: 10
        nick_name:
          type: string
          description: >-
            Name by which the player will be listed in brackets, scoring sheets,
            leaderboards, etc. (updatable).  If `nick_name` is not specified (or emptied
            out), the player will be listed by last name.
          example: Abs
        champ:
          type: boolean
          description: >-
            Signifies player as member of prior year winning team (used for partner
            assignment).
          example: false
        seed_wins:
          type: integer
          description: Wins during seeding round play.
        seed_losses:
          type: integer
          description: Losses during seeding round play.
        seed_pts_for:
          type: integer
          description: Total points scored during seeding round play.
        seed_pts_against:
          type: integer
          description: Total points by opponents during seeding round play.
        player_rank:
          type: integer
          description: >-
            Rank computed after seeding round play (used to determine order of partner
            picks).  Value is `null` if seeding round is not complete.
          example: null
      additionalProperties: true
    SeedGameData:
      type: object
      description: >-
        Seeding round game information (updatable fields indicated).  Each record
        represents either an indidvidual matchup within the seeding bracket, or a
        placeholder indicating the player or players with byes for a given round.
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        label:
          type: string
          description: >-
            Unique game identifier, prefixed by bracket indicator ("sd", "rr, "sf", "fn")
            followed by division (round robin only), round number, and table number.
            Record specifying teams having a bye for the round, will have "bye" indicated
            as the table number.
          example: rr-1-4-3
        round_num:
          type: integer
          description: >-
            Round number for the tournament stage (up to 8, for seeding and round robin
            bracket play; up to 3 for playoff brackets).
          example: 4
        player_nums:
          type: string
          description: >-
            Representation of the matchup, using "player number" identifiers.  The
            matchups are taken directly from precomputed bracket specifications (based on
            number of players and rounds).
          example: 1 / 3 vs. 5 / 11
        team1_name:
          type: string
          description:
          example: Watkins / Romeo
        team2_name:
          type: string
          description:
          example: Rooze / Springo
        bye_players:
          type: string
          description: Name of player(s) with bye(s) for the round.
          example: null
        team1_pts:
          type: integer
          description: >-
            Number of points for Team 1 (`null` if game has not yet been played and/or
            completed).
          example: null
        team2_pts:
          type: integer
          description: >-
            Number of points for Team 2 (`null` if game has not yet been played and/or
            completed).
          example: null
        winner:
          type: string
          description: >-
            Name of the winning team (`null` if game has not yet been played and/or
            completed).
          example: null
    PartnerData:
      type: object
      description: Partner picking information (updatable fields indicated).
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        player_rank:
          type: integer
          description: >-
            Player rank computed after seeding round play, which represents the order of
            partner picks.
          example: 5
        full_name:
          type: string
          description: >-
            Full name of player, composed of last name qualified by either first name or
            nick name (if specified).
          example: Abernathy (Abs)
        player_num:
          type: integer
          description: >-
            "Player number" identifier based on ping pong ball selection, or randomly
            generated values (updatable).  This identifier is used in assigning the player
            to seeding bracket matchups.
          example: 10
        champ:
          type: boolean
          description: >-
            Indicates that player was a member of prior year's winning team, which is
            always kept intact for a title defense.
          example: false
        available:
          type: boolean
          description: Indicates that the player is not yet assigned to a team.
          example: true
        picks_info:
          type: [string, integer]
          description: >-
            When representing the current partner pick, specify either the player's rank
            or name (or unique name prefix).  This is the only updatable field for the
            request.  When indicating completed picks, shows both the partner name and
            rank.
        picked_by_info:
          type: string
          description: >-
            Name and rank of the player who picked the player for the current record as a
            partner.
      additionalProperties: true
    TeamData:
      type: object
      description: >-
        Team information and round robin game stats (currently no updatable fields).
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        team_seed:
          type: integer
          description: >-
            Overall team seed based on average rank of players.  This value is used for
            assignment to divisions, and seed within the division, which are mapped to
            precomputed round robin bracket matchups.
          example: 7
        player_nums:
          type: string
          description: >-
            "Player number" identifiers for team members.
          example: 15 / 40
        team_name:
          type: string
          description: >-
            Name of team, which is a concatenation of team member names (nick name or last
            name).
          example: Cooper / Heitner
        div_num:
          type: integer
          description: Division to which team is assigned.
          example: 2
        div_seed:
          type: integer
          description: >-
            Team's seed within the division (maps to games specified in precomputed
            bracket matchups).
          example: 4
        tourn_wins:
          type: integer
          description: Wins during round robin play.
        tourn_losses:
          type: integer
          description: Losses during round robin play.
        tourn_pts_for:
          type: integer
          description: Total points scored during round robin play.
        tourn_pts_against:
          type: integer
          description: Total points by opponents during round robin play.
        tourn_rank:
          type: integer
          description: >-
            Overall team rank (based on win percentage and points percentage), computed
            after round robin play.  This value does not determine playoff teams, but is
            used as a factor in computing final tournament ranking.  Value is `null` if
            round robin play is not complete.
          example: null
        div_rank:
          type: integer
          description: >-
            Rank within the division, computed after round robin play.  Top two teams in
            each division will advance to the playoff round.  Value is `null` if round
            robin play is not complete.
          example: null
        final_rank:
          type: integer
          description: >-
            Final tournament rank, computed after playoff are complete.  Value is `null`
            if playoffs are not complete.
          example: null
      additionalProperties: true
    TournGameData:
      type: object
      description: >-
        Round robin game information (updatable fields indicated).  Each record represents
        either an indidvidual matchup within the round robin bracket, or a placeholder
        indicating a team that has a bye for a given round.
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        label:
          type: string
          description: >-
            Unique game identifier, prefixed by bracket indicator ("sd", "rr, "sf", "fn")
            followed by division (round robin only), round number, and table number.
            Record specifying the team having a bye for the round, will have "bye"
            indicated as the table number.
          example: rr-1-4-3
        div_num:
          type: integer
          description: Division number for the game.
          example: 2
        round_num:
          type: integer
          description: >-
            Round number for the tournament stage (up to 8, for round robin and round robin
            bracket play; up to 3 for playoff brackets).
          example: 4
        team_seeds:
          type: string
          description: >-
            Representation of the matchup, using division seed for the teams.  The
            matchups are taken directly from precomputed bracket specifications (based on
            number of teams and rounds).
          example: 4 vs. 10
        team1_name:
          type: string
          description:
          example: Frankel / Ponzio
        team2_name:
          type: string
          description:
          example: House / Della Grotte / Latt
        bye_team:
          type: string
          description: Name of team with a bye for the round.
          example: null
        team1_pts:
          type: integer
          description: >-
            Number of points for Team 1 (`null` if game has not yet been played and/or
            completed).
          example: null
        team2_pts:
          type: integer
          description: >-
            Number of points for Team 2 (`null` if game has not yet been played and/or
            completed).
          example: null
        winner:
          type: string
          description: >-
            Name of the winning team (`null` if game has not yet been played and/or
            completed).
          example: null
    PlayoffTeamData:
      type: object
      description: >-
        Final four team information and playoff game stats (currently no updatable fields).
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        tourn_rank:
          type: integer
          description: >-
            Overall team rank based round robin play.  This value is used purely for
            identification purposes.
          example: 3
        team_name:
          type: string
          description: >-
            Name of team, which is a concatenation of team member names (nick name or last
            name).
          example: Cooper / Heitner
        div_num:
          type: integer
          description: Division to which team is assigned.
          example: 2
        div_rank:
          type: integer
          description: >-
            Team's rank within the division after round robin play.  Each division's top
            ranked team plays the second ranked team from the other division in the
            semifinals.  The winners of each semis matchup play in the finals round.
          example: 1
        playoff_wins:
          type: integer
          description: Wins during playoff rounds.
        playoff_losses:
          type: integer
          description: Losses during playoff rounds.
        playoff_pts_for:
          type: integer
          description: Total points scored during playoff rounds.
        playoff_pts_against:
          type: integer
          description: Total points by opponents during playoff rounds.
        playoff_rank:
          type: integer
          description: >-
            Final four team rank based on advancement and finals play (and win and points
            stats for third and fourth place).  Note that provisional values are computed
            during playoff play (based on win and points stats).
          example: null
      additionalProperties: true
    PlayoffGameData:
      type: object
      description: >-
        Playofffs game information (updatable fields indicated).  Each record represents
        an indidvidual matchup within the playoffs bracket.
      properties:
        id:
          type: integer
          description: Internal database id (should not be visible in app interfaces).
        label:
          type: string
          description: >-
            Unique game identifier, prefixed by bracket indicator ("sd", "rr, "sf", "fn")
            followed by division (round robin only), round number, and table number.
            Record specifying the team having a bye for the round, will have "bye"
            indicated as the table number.
          example: sf-1-1
        bracket_ident:
          type: string
          description: Identifier for the playoff round (either semifinals or finals).
          example: Semifinals
        matchup_num:
          type: integer
          description: >-
            Matchup identifier within the playoff round (1 or 2 for semifinals, 1 for finals).
          example: 1
        round_num:
          type: integer
          description:  Game number within the match (best 2-out-of-3).
          example: 2
        team_ranks:
          type: string
          description: >-
            Representation of the matchup, using overall tournament rank (after round
            robin play) as identifiers for the teams.
          example: 1 vs. 4
        team1_name:
          type: string
          description:
          example: Frankel / Ponzio
        team2_name:
          type: string
          description:
          example: House / Della Grotte / Latt
        team1_pts:
          type: integer
          description: >-
            Number of points for Team 1 (`null` if game has not yet been played and/or
            completed).
          example: null
        team2_pts:
          type: integer
          description: >-
            Number of points for Team 2 (`null` if game has not yet been played and/or
            completed).
          example: null
        winner:
          type: string
          description: >-
            Name of the winning team (`null` if game has not yet been played and/or
            completed).
          example: null
